#!/bin/bash
#
# This file was automatically generated by s2e-env at 2026-02-10 22:19:44.039850
#
# This bootstrap script is used to control the execution of the target program
# in an S2E guest VM.
#
# When you run launch-s2e.sh, the guest VM calls s2eget to fetch and execute
# this bootstrap script. This bootstrap script and the S2E config file
# determine how the target program is analyzed.
#

set -x

cd /c/s2e

mkdir -p guest-tools32
TARGET_TOOLS32_ROOT=guest-tools32

mkdir -p guest-tools64
TARGET_TOOLS64_ROOT=guest-tools64

# 64-bit tools take priority on 64-bit architectures
TARGET_TOOLS_ROOT=${TARGET_TOOLS64_ROOT}

# To save the hassle of rebuilding guest images every time you update S2E's guest tools,
# the first thing that we do is get the latest versions of the guest tools.
function update_common_tools {
    local OUR_S2ECMD

    OUR_S2ECMD=${S2ECMD}

    # Windows does not allow s2ecmd.exe to overwrite itself, so we need a workaround.
    if echo ${COMMON_TOOLS} | grep -q s2ecmd; then
      OUR_S2ECMD=${S2ECMD}_old.exe
      mv ${S2ECMD} ${OUR_S2ECMD}
    fi

    for TOOL in ${COMMON_TOOLS}; do
        ${OUR_S2ECMD} get ${TARGET_TOOLS_ROOT}/${TOOL}
        if [ ! -f ${TOOL} ]; then
          ${OUR_S2ECMD} kill 0 "Could not get ${TOOL} from the host. Make sure that guest tools are installed properly."
          exit 1
        fi
        chmod +x ${TOOL}
    done
}

function update_target_tools {
    for TOOL in $(target_tools); do
        ${S2ECMD} get ${TOOL} ${TOOL}
        chmod +x ${TOOL}
    done
}

function prepare_target {
    # Make sure that the target is executable
    chmod +x "$1"
}

function get_ramdisk_root {
  echo 'x:\'
}

function copy_file {
  SOURCE="$1"
  DEST="$2"

  run_cmd "copy /Y ${SOURCE} ${DEST}" > /dev/null
}

# This prepares the symbolic file inputs.
# This function takes as input a seed file name and makes its content symbolic according to the symranges file.
# It is up to the host to prepare all the required symbolic files. The bootstrap file does not make files
# symbolic on its own.
function download_symbolic_file {
  SYMBOLIC_FILE="$1"
  RAMDISK_ROOT="$(get_ramdisk_root)"

  ${S2ECMD} get "${SYMBOLIC_FILE}"
  if [ ! -f "${SYMBOLIC_FILE}" ]; then
    ${S2ECMD} kill 1 "Could not fetch symbolic file ${SYMBOLIC_FILE} from host"
  fi

  copy_file "${SYMBOLIC_FILE}" "${RAMDISK_ROOT}"

  SYMRANGES_FILE="${SYMBOLIC_FILE}.symranges"

  ${S2ECMD} get "${SYMRANGES_FILE}" > /dev/null

  # Make the file symbolic
  if [ -f "${SYMRANGES_FILE}" ]; then
     export S2E_SYMFILE_RANGES="${SYMRANGES_FILE}"
  fi

  # The symbolic file will be split into symbolic variables of up to 4k bytes each.
  ${S2ECMD} symbfile 4096 "${RAMDISK_ROOT}${SYMBOLIC_FILE}" > /dev/null
}

function download_symbolic_files {
  for f in "$@"; do
    download_symbolic_file "${f}"
  done
}

# This function executes the target program given in arguments.
#
# There are two versions of this function:
#    - without seed support
#    - with seed support (-s argument when creating projects with s2e_env)
function execute {
    local TARGET

    TARGET="$1"
    shift

    execute_target "${TARGET}" "$@"
}

###############################################################################
# This section contains target-specific code

function make_seeds_symbolic {
    echo 1
}

# This function executes the target program.
# You can customize it if your program needs special invocation,
# custom symbolic arguments, etc.
function execute_target {
    run_cmd "$@"
}

# In 64-bit mode, it is important to run commands using the 64-bit cmd.exe,
# otherwise most changes will be confined to the SysWow64 environment.
# This function takes care of calling the right cmd.exe depending on the guest OS.
function run_cmd {
    local PREFIX
    local CMD
    CMD="$1"
    shift

    # The driver must be installed by a 64-bit process, otherwise
    # its files are copied into syswow64.
    # We use /c/Windows/sysnative to access 64-bit apps from 32-bit msys.
    PREFIX=/c/Windows/sysnative/

    ${PREFIX}cmd.exe //c "${CMD}" "$@"
}

function install_driver {
    local PREFIX
    local DRIVER
    DRIVER="$1"

    run_cmd "rundll32.exe setupapi,InstallHinfSection DefaultInstall 132 ${DRIVER}"
}

function disable_defender {
    echo "[defender] disabling realtime protection/services/policies"

    # Best-effort: some commands may fail depending on Tamper Protection/policy.
    run_cmd "powershell -ExecutionPolicy Bypass -Command \"Set-MpPreference -DisableRealtimeMonitoring \$true\"" || true
    run_cmd "powershell -ExecutionPolicy Bypass -Command \"Set-MpPreference -DisableBehaviorMonitoring \$true\"" || true
    run_cmd "powershell -ExecutionPolicy Bypass -Command \"Set-MpPreference -DisableScriptScanning \$true\"" || true
    run_cmd "powershell -ExecutionPolicy Bypass -Command \"Set-MpPreference -MAPSReporting 0\"" || true
    run_cmd "powershell -ExecutionPolicy Bypass -Command \"Set-MpPreference -SubmitSamplesConsent 2\"" || true

    run_cmd "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\" /v DisableAntiSpyware /t REG_DWORD /d 1 /f" || true
    run_cmd "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\" /v DisableAntiVirus /t REG_DWORD /d 1 /f" || true
    run_cmd "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Real-Time Protection\" /v DisableRealtimeMonitoring /t REG_DWORD /d 1 /f" || true
    run_cmd "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Real-Time Protection\" /v DisableBehaviorMonitoring /t REG_DWORD /d 1 /f" || true
    run_cmd "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Real-Time Protection\" /v DisableOnAccessProtection /t REG_DWORD /d 1 /f" || true
    run_cmd "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Real-Time Protection\" /v DisableScanOnRealtimeEnable /t REG_DWORD /d 1 /f" || true

    run_cmd "sc stop WinDefend" || true
    run_cmd "sc stop WdNisSvc" || true
    run_cmd "sc stop Sense" || true
    run_cmd "sc stop SecurityHealthService" || true
    run_cmd "sc config WinDefend start= disabled" || true
    run_cmd "sc config WdNisSvc start= disabled" || true
    run_cmd "sc config Sense start= disabled" || true
    run_cmd "sc config SecurityHealthService start= disabled" || true
}

function target_init {
    echo "[target_init] RUN_TARGET_INIT=${RUN_TARGET_INIT:-<unset>} S2E_DISABLE_DEFENDER=${S2E_DISABLE_DEFENDER:-<unset>}"
    # Keep target init minimal and deterministic.
    # The ready snapshot already contains installed components.
    run_cmd "reg add HKLM\\Software\\S2E /v FaultInjectionEnabled /t REG_DWORD /d 0 /f"
    # Install driver if missing; optional forced reinstall via env.
    local HAS_S2E_SERVICE=0
    if run_cmd "sc query s2e >nul 2>nul"; then
        HAS_S2E_SERVICE=1
    fi

    if [ "${S2E_REINSTALL_DRIVER:-0}" = "1" ] || [ "${HAS_S2E_SERVICE}" = "0" ]; then
        install_driver 'c:\s2e\s2e.inf'
    fi

    # Optional precondition for service-gated malware paths:
    # create HKLM\SYSTEM\CurrentControlSet\Services\<name>\DisplayName.
    # Enable by setting:
    #   S2E_GATE_SERVICE_NAME=<service_name>
    # Optional:
    #   S2E_GATE_DISPLAY_NAME=<display_name>
    if [ -n "${S2E_GATE_SERVICE_NAME:-}" ]; then
        local GATE_SVC_NAME="${S2E_GATE_SERVICE_NAME}"
        local GATE_SVC_DISPLAY="${S2E_GATE_DISPLAY_NAME:-$GATE_SVC_NAME}"
        run_cmd "reg add HKLM\\SYSTEM\\CurrentControlSet\\Services\\${GATE_SVC_NAME} /f"
        run_cmd "reg add HKLM\\SYSTEM\\CurrentControlSet\\Services\\${GATE_SVC_NAME} /v DisplayName /t REG_SZ /d \"${GATE_SVC_DISPLAY}\" /f"
    fi

    run_cmd "sc start s2e"
    run_cmd "sc query s2e"
    drvctl.exe register_debug

    # Default to not touching Defender; explicit opt-in only.
    if [ "${S2E_DISABLE_DEFENDER:-0}" = "1" ]; then
        disable_defender
    fi
}

function ensure_ramdisk {
    # Needed only for file-input mode.
    imdisk -D -m X: > /dev/null 2> /dev/null || true
    imdisk -a -s 2M -m X: -p "/fs:fat /q /y"
}

function target_tools {
    echo ""
}

# This function converts an msys path into a Windows path
function win_path {
  local dir="$(dirname "$1")"
  local fn="$(basename "$1")"
  echo "$(cd "$dir"; echo "$(pwd -W)/$fn")" | sed 's|/|\\|g';
}

S2ECMD=./s2ecmd.exe
S2EGET=./s2eget.exe
S2EPUT=./s2eput.exe
COMMON_TOOLS="s2ecmd.exe s2e.sys s2e.inf drvctl.exe tickler.exe"
COMMON_TOOLS="${COMMON_TOOLS} libs2e32.dll libs2e64.dll"

###############################################################################

update_common_tools
update_target_tools

# Optional host-provided guest init controls.
# Format (guest-init.txt):
#   RUN_TARGET_INIT=<0|1>
#   S2E_DISABLE_DEFENDER=<0|1>
${S2ECMD} get "guest-init.txt" > /dev/null 2> /dev/null || true
if [ -f "guest-init.txt" ]; then
    while IFS='=' read -r KEY VAL; do
        KEY="$(echo "${KEY}" | tr -d '\r\n\t ')"
        VAL="$(echo "${VAL}" | tr -d '\r\n\t ')"
        case "${KEY}" in
            RUN_TARGET_INIT)
                if [ -n "${VAL}" ]; then
                    RUN_TARGET_INIT="${VAL}"
                fi
                ;;
            S2E_DISABLE_DEFENDER)
                if [ -n "${VAL}" ]; then
                    S2E_DISABLE_DEFENDER="${VAL}"
                fi
                ;;
        esac
    done < "guest-init.txt"
fi
echo "[guest-init] RUN_TARGET_INIT=${RUN_TARGET_INIT:-<unset>} S2E_DISABLE_DEFENDER=${S2E_DISABLE_DEFENDER:-<unset>}"

# Target init is required for WindowsMonitor/guest event tracking.
if [ "${RUN_TARGET_INIT:-1}" = "1" ]; then
    target_init
fi

TARGET_HOST_FILE="${S2E_TARGET_FILE:-target.exe}"
TARGET_GUEST_BASENAME="${S2E_TARGET_GUEST_BASENAME:-$(basename "${TARGET_HOST_FILE}")}"
TARGET_PATH="${S2E_TARGET_GUEST_PATH:-c:\\s2e\\${TARGET_GUEST_BASENAME}}"

# Download the target file to analyze
${S2ECMD} get "${TARGET_HOST_FILE}" "${TARGET_GUEST_BASENAME}"
${S2ECMD} get "dll-run.txt" > /dev/null 2> /dev/null || true

# Resolve mode in this order:
#  1) guest env INPUT_MODE
#  2) project file input-mode.txt (fetched from host)
#  3) default: c2pid
if [ -z "${INPUT_MODE}" ]; then
    ${S2ECMD} get "input-mode.txt" > /dev/null 2> /dev/null
    if [ -f "input-mode.txt" ]; then
        INPUT_MODE="$(tr -d '\r\n' < input-mode.txt)"
    fi
fi
INPUT_MODE="${INPUT_MODE:-c2pid}"

if [ "${INPUT_MODE}" = "file" ]; then
    ensure_ramdisk
    # Download and symbolicize file input.
    download_symbolic_files "input-0"
fi

# Run the analysis
RUN_DLL_MODE="${RUN_DLL:-0}"
DLL_NAME="${S2E_DLL_NAME:-}"
DLL_EXPORT="${S2E_DLL_EXPORT:-Install}"
DLL_EXEC_TIMEOUT="${S2E_DLL_EXEC_TIMEOUT:-45}"

# Prefer host control-file mode for deterministic DLL replay.
# Format (dll-run.txt):
#   line1: DLL filename in project dir
#   line2: export name (optional, default Install)
if [ -f "dll-run.txt" ]; then
    RUN_DLL_MODE=1
    DLL_NAME="$(sed -n '1p' dll-run.txt | tr -d '\r\n')"
    _DLL_EXPORT_FROM_FILE="$(sed -n '2p' dll-run.txt | tr -d '\r\n')"
    if [ -n "${_DLL_EXPORT_FROM_FILE}" ]; then
        DLL_EXPORT="${_DLL_EXPORT_FROM_FILE}"
    fi
fi

if [ "${RUN_DLL_MODE}" = "1" ]; then
    if [ -z "${DLL_NAME}" ]; then
        ${S2ECMD} kill 1 "RUN_DLL=1 requires S2E_DLL_NAME (host filename under project dir)"
    fi
    ${S2ECMD} get "${DLL_NAME}" "${DLL_NAME}"
    if [ ! -f "${DLL_NAME}" ]; then
        ${S2ECMD} kill 1 "Could not fetch DLL ${DLL_NAME} from host project dir"
    fi
    DLL_WIN_PATH="c:\\s2e\\${DLL_NAME}"

    # Support either a single export or comma-separated export list.
    DLL_EXPORT_CSV="${DLL_EXPORT}"
    if [ -z "${DLL_EXPORT_CSV}" ]; then
        DLL_EXPORT_CSV="Install"
    fi

    OLD_IFS="${IFS}"
    IFS=','
    set -- ${DLL_EXPORT_CSV}
    IFS="${OLD_IFS}"

    EXP_TOTAL=$#
    EXP_IDX=0
    for EXP_RAW in "$@"; do
        EXP_IDX=$((EXP_IDX + 1))
        EXP_NAME="$(echo "${EXP_RAW}" | sed 's/^ *//; s/ *$//')"
        if [ -z "${EXP_NAME}" ]; then
            continue
        fi

        echo "[dllmulti] begin idx=${EXP_IDX}/${EXP_TOTAL} dll=${DLL_NAME} export=${EXP_NAME}"
        set +e
        execute "rundll32.exe" "${DLL_WIN_PATH},${EXP_NAME}" &
        RUNNER_PID=$!
        (
            sleep "${DLL_EXEC_TIMEOUT}"
            run_cmd "taskkill /F /IM rundll32.exe" > /dev/null 2> /dev/null || true
        ) &
        KILLER_PID=$!
        wait "${RUNNER_PID}"
        EXP_RC=$?
        kill "${KILLER_PID}" > /dev/null 2> /dev/null || true
        set -e
        echo "[dllmulti] end idx=${EXP_IDX}/${EXP_TOTAL} dll=${DLL_NAME} export=${EXP_NAME} rc=${EXP_RC}"
    done
else
    if [ ! -f "${TARGET_GUEST_BASENAME}" ]; then
        ${S2ECMD} kill 1 "Could not fetch target ${TARGET_HOST_FILE} from host project dir"
    fi
    prepare_target "${TARGET_PATH}"

    if [ "${INPUT_MODE}" = "api" ] || [ "${INPUT_MODE}" = "c2" ] || [ "${INPUT_MODE}" = "c2pid" ]; then
        # Interactive/API-input target mode (including C2 emulation).
        execute "${TARGET_PATH}"
    else
        # File-input target mode.
        execute "${TARGET_PATH}" 'x:\input-0'
    fi
fi
