#!/bin/bash
#
# This file was automatically generated by s2e-env at 2026-02-10 22:19:44.039850
#
# This script is used to run the S2E analysis. Additional QEMU command line
# arguments can be passed to this script at run time.
#

ENV_DIR="/home/tako/hjyoo/s2e"
INSTALL_DIR="$ENV_DIR/install"
BUILD_DIR="$ENV_DIR/build"
BUILD=debug

# Either s2e for symbolic execution support or s2e_sp for single-path mode
S2E_MODE=s2e
DEBUG=""

if [ "x$GUI" != "x1" ]; then
  GRAPHICS=-nographic
fi

if [ "x$1" = "xdebug" ]; then
  DEBUG=1
  shift
fi

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_DIR"


IMAGE_PATH="$ENV_DIR/images/windows-10pro1909-x86_64/image.raw.s2e"
IMAGE_JSON="$(dirname $IMAGE_PATH)/image.json"

if [ ! -f "$IMAGE_PATH" -o ! -f "$IMAGE_JSON" ]; then
    echo "$IMAGE_PATH and/or $IMAGE_JSON do not exist. Please check that your images are built properly."
    exit 1
fi

# Prevent multiple QEMU instances from using the same image at once.
RUNNING_QEMU=$(pgrep -af "qemu-system-x86_64.*$IMAGE_PATH" || true)
if [ "x$RUNNING_QEMU" != "x" ]; then
    echo "Another QEMU instance is already running with $IMAGE_PATH"
    echo "$RUNNING_QEMU"
    echo "Stop existing instance before starting a new run."
    exit 1
fi

QEMU_DRIVE="-drive file=$IMAGE_PATH,format=s2e,cache=writeback"
QEMU_EXTRA_FLAGS=$(jq -r '.qemu_extra_flags' "$IMAGE_JSON")
QEMU_MEMORY=$(jq -r '.memory' "$IMAGE_JSON")
QEMU_SNAPSHOT=$(jq -r '.snapshot' "$IMAGE_JSON")

# Optional override for debugging snapshot issues.
# Usage:
#   DISABLE_SNAPSHOT=1 ./launch-s2e.sh
#   S2E_SNAPSHOT_NAME=ready ./launch-s2e.sh
if [ "x$DISABLE_SNAPSHOT" = "x1" ]; then
    QEMU_SNAPSHOT=""
fi

if [ "x$S2E_SNAPSHOT_NAME" != "x" ]; then
    QEMU_SNAPSHOT="$S2E_SNAPSHOT_NAME"
fi




export S2E_CONFIG=s2e-config.lua
export S2E_SHARED_DIR=$INSTALL_DIR/share/libs2e
export S2E_MAX_PROCESSES=1
export S2E_UNBUFFERED_STREAM=1
export S2E_PROJECT_DIR="$PROJECT_DIR"

# Project defaults for c2pid workflow (can be overridden from shell).
export S2E_C2_MODE="${S2E_C2_MODE:-hybrid}"
export S2E_C2_SCENARIO_FILE="${S2E_C2_SCENARIO_FILE:-$PROJECT_DIR/c2-scenarios.hybrid.lua}"
export S2E_C2_SCENARIO="${S2E_C2_SCENARIO:-auto_hybrid}"
export S2E_C2_TRACE_COMPARE="${S2E_C2_TRACE_COMPARE:-1}"
export S2E_C2_GUIDE_COMPARE="${S2E_C2_GUIDE_COMPARE:-0}"
export S2E_C2_FORCE_COMPARE_PASS="${S2E_C2_FORCE_COMPARE_PASS:-1}"
export S2E_C2_COMPARE_AFTER_NET_ONLY="${S2E_C2_COMPARE_AFTER_NET_ONLY:-1}"
export S2E_C2_COMPARE_AFTER_NET_BUDGET="${S2E_C2_COMPARE_AFTER_NET_BUDGET:-64}"
export S2E_C2PID_DEBUG="${S2E_C2PID_DEBUG:-1}"
export S2E_C2_KILL_NON_TARGET_AFTER_TRACK="${S2E_C2_KILL_NON_TARGET_AFTER_TRACK:-1}"
export S2E_C2_GLOBAL_TRACE="${S2E_C2_GLOBAL_TRACE:-0}"
export S2E_C2_COMPARE_FALLBACK_MODULES="${S2E_C2_COMPARE_FALLBACK_MODULES:-rundll32.exe}"
export S2E_C2_GATE_MIN_READ="${S2E_C2_GATE_MIN_READ:-0}"
export S2E_C2_GATE_SIZE_OFF="${S2E_C2_GATE_SIZE_OFF:--1}"
export S2E_C2_GATE_SIZE_OFFSETS="${S2E_C2_GATE_SIZE_OFFSETS:-}"
export S2E_C2_GATE_SIZE_VALUE="${S2E_C2_GATE_SIZE_VALUE:-n}"
export S2E_C2_GATE_MAGIC_OFF="${S2E_C2_GATE_MAGIC_OFF:--1}"
export S2E_C2_GATE_MAGIC_HEX="${S2E_C2_GATE_MAGIC_HEX:-}"
export S2E_C2_GATE_MAGIC_PATCHES="${S2E_C2_GATE_MAGIC_PATCHES:-}"
export S2E_C2_FORCE_NET_EMULATION="${S2E_C2_FORCE_NET_EMULATION:-0}"
export S2E_C2_FORCE_NET_PROGRESS="${S2E_C2_FORCE_NET_PROGRESS:-1}"
export S2E_C2_FORCE_CONNECT_CALL="${S2E_C2_FORCE_CONNECT_CALL:-1}"
export S2E_C2_FORCE_RECV_N="${S2E_C2_FORCE_RECV_N:-64}"
export S2E_C2_FORCE_RECV_USE_REQ="${S2E_C2_FORCE_RECV_USE_REQ:-1}"
export S2E_C2_FORCE_SELECT_READY="${S2E_C2_FORCE_SELECT_READY:-1}"
export S2E_C2_DISABLE_INJECT="${S2E_C2_DISABLE_INJECT:-1}"
export S2E_C2_KILL_ON_TARGET_EXIT="${S2E_C2_KILL_ON_TARGET_EXIT:-0}"
export S2E_C2_SUPPRESS_TARGET_EXIT="${S2E_C2_SUPPRESS_TARGET_EXIT:-1}"
export S2E_DISABLE_DEFENDER="${S2E_DISABLE_DEFENDER:-1}"
export RUN_TARGET_INIT="${RUN_TARGET_INIT:-1}"
export S2E_REINSTALL_DRIVER="${S2E_REINSTALL_DRIVER:-0}"
export S2E_INPUT_MODE="${S2E_INPUT_MODE:-c2pid}"

# Auto-select guest DLL architecture for export resolution.
# PE32 samples on x64 Windows load user-mode DLLs from SysWOW64.
if [ -z "${S2E_C2_DLL_ARCH:-}" ]; then
    if file -L "$PROJECT_DIR/test.exe" 2>/dev/null | grep -q "PE32 executable"; then
        export S2E_C2_DLL_ARCH="wow64"
    else
        export S2E_C2_DLL_ARCH="native"
    fi
fi

if [ $S2E_MAX_PROCESSES -gt 1 ]; then
    # Multi-threaded mode does not support graphics output, so we override
    # whatever settings were there before.
    export GRAPHICS=-nographic
fi

QEMU_ARGS="-k en-us -monitor null -enable-kvm -serial file:serial.txt $GRAPHICS -m $QEMU_MEMORY $QEMU_EXTRA_FLAGS"

if [ "x$QEMU_DRIVE" != "x" ]; then
    QEMU_ARGS="$QEMU_ARGS $QEMU_DRIVE"
fi

if [ "x$QEMU_SNAPSHOT" != "x" ]; then
    QEMU_ARGS="$QEMU_ARGS -loadvm $QEMU_SNAPSHOT"
fi

if [ "x$QEMU_BIOS" != "x" ]; then
    QEMU_ARGS="$QEMU_ARGS $QEMU_BIOS"
    QEMU_ARGS="$QEMU_ARGS -chardev stdio,id=seabios -device isa-debugcon,iobase=0x402,chardev=seabios"
fi

if [ "x$DEBUG" != "x" ]; then

    if [ ! -d "$BUILD_DIR/qemu-$BUILD" ]; then
        echo "No debug build found in $BUILD_DIR/qemu-$BUILD. Please run \`\`s2e build -g\`\`"
        exit 1
    fi

    QEMU="$BUILD_DIR/qemu-$BUILD/x86_64-softmmu/qemu-system-x86_64"
    LIBS2E="$BUILD_DIR/libs2e-$BUILD/x86_64-$S2E_MODE-softmmu/libs2e.so"

    rm -f gdb.ini

    cat <<EOF >gdb.ini
    handle SIGUSR1 noprint
    handle SIGUSR2 noprint
    set disassembly-flavor intel
    set print pretty on
    set environment S2E_CONFIG=$S2E_CONFIG
    set environment S2E_SHARED_DIR=$S2E_SHARED_DIR
    set environment LD_PRELOAD=$LIBS2E
    set environment S2E_UNBUFFERED_STREAM=1
    # set environment LIBCPU_LOG_LEVEL=in_asm,int,exec
    # set environment LIBCPU_LOG_FILE=/tmp/log.txt
    # set environment S2E_QMP_SERVER=127.0.0.1:3322
    set python print-stack full

python
import sys
sys.path.insert(0, '/usr/share/gcc/python')
from libstdcxx.v6.printers import register_libstdcxx_printers
register_libstdcxx_printers (None)
end
EOF

    GDB="gdb  --init-command=gdb.ini --args"

    # Useful options:
    # - Display debug output from the BIOS:
    #    -chardev stdio,id=seabios -device isa-debugcon,iobase=0x402,chardev=seabios

    $GDB $QEMU $QEMU_ARGS $*

else
    QEMU="$INSTALL_DIR/bin/qemu-system-x86_64"
    LIBS2E="$INSTALL_DIR/share/libs2e/libs2e-x86_64-$S2E_MODE.so"

    LD_PRELOAD=$LIBS2E $QEMU $QEMU_ARGS $* &

    CHILD_PID=$!
    trap "kill $CHILD_PID" SIGINT
    wait $CHILD_PID
fi
